version: '3.4'
services:
  clipboard:
    container_name: clipboard
    image: clipboard:1.0
    volumes:
      - /var/www/clipboard/:/var/www/clipboard/
      - /var/log/:/var/log/
    restart: always
    ports:
      - 80:4000
    privileged: true
